name: Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SetupNode
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: InstallDependencies
        run: npm install
        
      - name: Compile
        run: npx tsc
          
      - name: RunTest
        run: node test.js
